[package]
name = "sqids"
description = "Generate YouTube-like ids from numbers."
repository = "https://github.com/sqids/sqids-rust"
documentation = "https://docs.rs/sqids"
homepage = "https://sqids.org/rust"
version = "0.3.1"
license = "MIT"
edition = "2021"
readme = "README.md"
keywords = ["ids", "encode", "short", "sqids", "hashids"]

[dependencies]
derive_builder = "0.12.0"
serde = "1.0.192"
serde_json = "1.0.108"
thiserror = "1.0.50"

[lib]
bench = false

[[bench]]
name = "basic"
harness = false

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[profile.bench]
opt-level = 2
codegen-units = 1
